language: clojure
sudo: required
services:
- docker
lein: lein
before_install:
- if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
  fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud version
- openssl aes-256-cbc -K $encrypted_e5f3d8a0584a_key -iv $encrypted_e5f3d8a0584a_iv
  -in service-account.json.enc -out service-account.json -d
script:
- lein package
- docker build -t favorite-albums:latest .
before_deploy:
- gzip -rk public
- cd public
- tar --exclude "js/release/*" -zcf ../deployment.tar.gz .
- cd ..
- git config --local user.name "Travis CI"
- git config --local user.email "builds@travis-ci.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk
env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
deploy:
  provider: releases
  api_key:
    secure: lM8JMmPfL3IQnLVXg7HIsetiUO3UqW7B5UeRywSBO2kRKyaSeJ45nDyJTUVvcElJ5hxFY/1c7CN3R+fHbVxyyHpba72h71RChrDbqsYXwV32N1HWmLqMJQZIFigZZGIXKdMWKIL71fzIdFpsm3jUhFcSpl6qFvNTtyIuB80GHfMRlCkpFEIErVJuHqyCr1mMzyZU3Bg0kokpUZb0kaT0tngkhCPME2avg91YM5KjuVkP3dhH9q+vUorDp/7zp6nlAgZKE/nmeZRl8EopVtu0sHzpnyUL40ZfCQubeLII4pPpQC5+bhaMpgGETwI7V0BIcfDPnEDlNBl5MovIQT7K037prKjJ1cNqwP6aCKPTrSFYRX1HkUenKvse7QR5lWxXvsb7upxtTXCfHNFNv2R+clOsJDWtbacwM00N3essqVQ3qSztcfacQNw7Wls4nW9T7AK1Q8jgpYdcTY34bhW7+eAr5F6ep97Pxm6LBNNW7blMDxxr0yominptqQdVf1383BLvkhoZNq8G6XRzDrP1gE6mRMlAP+HLfhJwnpNR+5rOl9goPthfK3hwp92Iu5H0T4Yqs0DZqvtALd5lmSCKMtVnApv3eKTXofhE1AVPv/FPH8jXmRnxgebia+OMWWhKNa2r+NPM2Bohe3fkWL+j/yc0RR+Jurj2OowHRoHAbaY=
  file: deployment.tar.gz
  skip_cleanup: true
  on:
    repo: tanelso2/favorite-albums-webapp
    branch: master
