language: clojure
sudo: required
services:
- docker
lein: lein
before_install:
- if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
  fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud version
- openssl aes-256-cbc -K $encrypted_e5f3d8a0584a_key -iv $encrypted_e5f3d8a0584a_iv
  -in service-account.json.enc -out service-account.json -d
script:
- lein package
- docker build -t $REPO_NAME:latest .
before_deploy:
- scripts/install_helm.sh
cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk
env:
  global:
  # Do not prompt for user input when using any SDK methods.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - REPO_NAME=favorite-albums
  - GCR_REPO=gcr.io/kubernetes-221218
  - HELM_RELEASE=crazy-ant
  - HELM_CHART_DIR=helm/favorite-albums
deploy:
- provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    repo: tanelso2/favorite-albums-webapp
    branch: master
